import{put}from'@vercel/blob';
import{cookie,unseal}from'../_instagram.js';
export const maxDuration=120;
function sameOrigin(req){let origin=req.headers.origin||'',protocol=(req.headers['x-forwarded-proto']||'https').split(',')[0],host=req.headers['x-forwarded-host']||req.headers.host;return origin===`${protocol}://${host}`}
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
async function graph(path,params,method='POST'){let url=new URL(`https://graph.instagram.com/v24.0/${path}`),options={method};if(method==='GET'){Object.entries(params).forEach(([k,v])=>url.searchParams.set(k,v))}else{options.headers={'Content-Type':'application/x-www-form-urlencoded'};options.body=new URLSearchParams(params)}let response=await fetch(url,options),body=await response.json();if(!response.ok)throw new Error(body.error?.message||'Instagram publishing request failed');return body}
async function ready(id,accessToken){let status='IN_PROGRESS';for(let attempt=0;attempt<18&&status==='IN_PROGRESS';attempt++){await wait(attempt?2000:1000);let check=await graph(id,{fields:'status_code,status',access_token:accessToken},'GET');status=check.status_code||'IN_PROGRESS';if(status==='ERROR'||status==='EXPIRED')throw new Error(check.status||`Instagram media processing ${status.toLowerCase()}`)}if(status!=='FINISHED')throw new Error('Instagram is still processing the media. Please retry publishing in a moment.')}
async function store(image,title,index){if(!image?.startsWith('data:image/')||image.length>8_000_000)throw new Error(`Slide ${index+1} is missing or too large`);let match=image.match(/^data:(image\/(?:jpeg|jpg|png));base64,(.+)$/);if(!match)throw new Error(`Slide ${index+1} must be JPG or PNG`);let contentType=match[1].replace('jpg','jpeg'),extension=contentType==='image/png'?'png':'jpg',safe=(title||'instagram-post').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60),options={access:'public',contentType,addRandomSuffix:true};if(process.env.BLOB_READ_WRITE_TOKEN)options.token=process.env.BLOB_READ_WRITE_TOKEN;return put(`instagram/${Date.now()}-${safe}-${index+1}.${extension}`,Buffer.from(match[2],'base64'),options)}
export default async function handler(req,res){if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});if(!sameOrigin(req))return res.status(403).json({error:'Origin not allowed'});let session=unseal(cookie(req,'scs_instagram'));if(!session?.accessToken||!session?.id)return res.status(401).json({error:'Connect Instagram in Settings first'});if(!process.env.BLOB_READ_WRITE_TOKEN&&!process.env.BLOB_STORE_ID)return res.status(503).json({error:'Media storage is not connected to this deployment. Redeploy after connecting the public Blob store.'});try{let{image,images,caption,title}=req.body||{},media=(Array.isArray(images)&&images.length?images:[image]).filter(Boolean).slice(0,10);if(!media.length)return res.status(400).json({error:'Finished media is required'});let blobs=[];for(let i=0;i<media.length;i++)blobs.push(await store(media[i],title,i));let creationId;if(blobs.length>1){let children=[];for(let blob of blobs){let child=await graph(`${session.id}/media`,{image_url:blob.url,is_carousel_item:'true',access_token:session.accessToken});if(!child.id)throw new Error('Instagram did not return a carousel item ID');await ready(child.id,session.accessToken);children.push(child.id)}let parent=await graph(`${session.id}/media`,{media_type:'CAROUSEL',children:children.join(','),caption:(caption||'').slice(0,2200),access_token:session.accessToken});if(!parent.id)throw new Error('Instagram did not return a carousel container ID');await ready(parent.id,session.accessToken);creationId=parent.id}else{let container=await graph(`${session.id}/media`,{image_url:blobs[0].url,caption:(caption||'').slice(0,2200),access_token:session.accessToken});if(!container.id)throw new Error('Instagram did not return a media container ID');await ready(container.id,session.accessToken);creationId=container.id}let published=await graph(`${session.id}/media_publish`,{creation_id:creationId,access_token:session.accessToken}),details=await graph(published.id,{fields:'id,permalink,timestamp',access_token:session.accessToken},'GET');return res.status(200).json({published:true,mediaId:published.id,permalink:details.permalink||'',timestamp:details.timestamp||new Date().toISOString(),imageUrl:blobs[0].url,imageUrls:blobs.map(x=>x.url),carousel:blobs.length>1})}catch(error){console.error('Instagram publish failed',error);return res.status(502).json({error:error.message||'Instagram publishing failed'})}}
