import{createHash,timingSafeEqual}from'node:crypto';
export const maxDuration=300;
const SYSTEM_STYLE=`Create a restrained, premium social-media image that feels art-directed and commercially photographed. Treat every uploaded image as source-of-truth material. Preserve the product's exact identity, silhouette, color, construction, texture, pattern, hardware and proportions. Never replace it with a similar product or invent missing details. Use one clear visual idea, generous negative space, natural lighting, subtle depth and a confident editorial composition. Keep the product dominant. Use at most two or three visual panels; one strong hero image is preferred. Render no more than 14 words total in the image: one short headline of 3–6 words and, only when necessary, one supporting line of up to 8 words. Never render paragraphs, repeated claims, multiple calls to action, feature lists, excessive labels, fake interfaces, watermarks, decorative clutter, neon or heavy gradients. Typography must be crisp, correctly spelled and secondary to the product.`;
function allowedOrigin(req){let origin=req.headers.origin||'',own=`https://${req.headers.host}`;return origin===own||origin===process.env.ALLOWED_ORIGIN?origin:''}
function authorized(req){let expected=process.env.GENERATION_ACCESS_KEY||'',cookie=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('scs_auth='))?.slice(9)||'',valid=expected?createHash('sha256').update(expected).digest('hex'):'';if(!cookie||!valid)return false;let a=Buffer.from(cookie),b=Buffer.from(valid);return a.length===b.length&&timingSafeEqual(a,b)}
function promptFor({idea,template,platform,brand,refinement,materialNames}){let concept=idea?.hook||idea?.title||'A premium product story',support=idea?.message||'';return `${SYSTEM_STYLE}\n\nOUTPUT: ${platform||'Instagram square'}, polished 1:1 social post.\nCREATIVE INTENT: ${template||'Product Spotlight'}.\nMESSAGE SOURCE: ${concept}. ${support}\nBRAND: ${brand?.name||'the supplied brand'}; voice: ${brand?.voice||'confident, concise and premium'}.\nSOURCE MATERIALS: ${(materialNames||[]).join(', ')||'uploaded product references'}. Use these references faithfully and visibly.\n\nCOPY DIRECTION: Distill the message source into a short, polished headline; do not copy the full sentence. Prefer a product-led composition with zero supporting copy when the image communicates the idea. Never exceed the 14-word image-copy limit.\n\nCOMPOSITION: Choose one hero product view and no more than two supporting details. Avoid montage density, redundant before/after cards, arrows, UI-like labels and repeated product cutouts. Keep important content inside generous safe margins.${refinement?`\n\nEDIT REQUEST: The first uploaded image is the current approved composition. Refine that composition—not a fresh redesign—using this direction: ${refinement}. Preserve everything not requested to change and continue using the remaining uploads as product-fidelity references.`:''}`}
export default async function handler(req,res){
  let origin=allowedOrigin(req);if(origin)res.setHeader('Access-Control-Allow-Origin',origin);
  if(req.method==='OPTIONS'){if(!origin)return res.status(403).end();res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization');return res.status(204).end()}
  if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});
  if(!origin)return res.status(403).json({error:'Origin not allowed'});
  if(!authorized(req))return res.status(401).json({error:'Invalid generation access key'});
  if(!process.env.OPENAI_API_KEY||!process.env.GENERATION_ACCESS_KEY)return res.status(500).json({error:'Backend secrets are not configured'});
  try{
    const{image,images,idea,template,platform,brand,refinement,materialNames}=req.body||{},sources=(Array.isArray(images)?images:[image]).filter(Boolean).slice(0,4);
    if(!sources.length||sources.some(x=>!x.startsWith('data:image/')||x.length>6_000_000))return res.status(400).json({error:'Add up to four valid product-reference images'});
    const response=await fetch('https://api.openai.com/v1/images/edits',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:'gpt-image-2',images:sources.map(image_url=>({image_url})),prompt:promptFor({idea,template,platform,brand,refinement,materialNames}),n:1,size:'1024x1024',quality:'high',output_format:'jpeg',output_compression:92})});
    const body=await response.json();
    if(!response.ok)throw new Error(body?.error?.message||'Image generation failed');
    const outputImages=(body.data||[]).map((x,i)=>({src:`data:image/jpeg;base64,${x.b64_json}`,width:1024,height:1024,style:['Product transformation','Quantified proof','Campaign story'][i]||`Direction ${i+1}`,platform:platform||'Instagram'}));
    return res.status(200).json({images:outputImages});
  }catch(error){return res.status(500).json({error:error.message||'Generation failed'})}
}
