import{createHash,timingSafeEqual}from'node:crypto';
export const maxDuration=300;
const SYSTEM_STYLE=`Create a restrained, premium social-media image that feels art-directed and commercially photographed. Treat every uploaded image as source-of-truth material. Preserve the product's exact identity, silhouette, color, construction, texture, pattern, hardware and proportions. Never replace it with a similar product or invent missing details. Use one clear visual idea, generous negative space, natural lighting, subtle depth and a confident editorial composition. Keep the product dominant. Use at most two or three visual panels; one strong hero image is preferred. Render no more than 14 words total in the image: one short headline of 3–6 words and, only when necessary, one supporting line of up to 8 words. Never render paragraphs, repeated claims, multiple calls to action, feature lists, excessive labels, fake interfaces, watermarks, decorative clutter, neon or heavy gradients. Typography must be crisp, correctly spelled and secondary to the product.`;
function allowedOrigin(req){let origin=req.headers.origin||'',own=`https://${req.headers.host}`;return origin===own||origin===process.env.ALLOWED_ORIGIN?origin:''}
function authorized(req){let expected=process.env.GENERATION_ACCESS_KEY||'',cookie=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('scs_auth='))?.slice(9)||'',valid=expected?createHash('sha256').update(expected).digest('hex'):'';if(!cookie||!valid)return false;let a=Buffer.from(cookie),b=Buffer.from(valid);return a.length===b.length&&timingSafeEqual(a,b)}
function promptFor({idea,template,platform,brand,refinement,materialNames,slideIndex,slideCount,sourceFocus}){let concept=idea?.hook||idea?.title||'A premium product story',support=idea?.message||'',roles=['Cover: one arresting product-led hook','Hero: show the product clearly and communicate the central benefit','Detail: reveal one meaningful material, feature or proof point','Context: place the exact product in a restrained lifestyle setting','Proof: communicate one credible outcome with minimal copy','Close: clean final product image with one concise call to action'],carousel=slideCount>1?`\nCAROUSEL: This is slide ${slideIndex+1} of ${slideCount}. Role: ${roles[slideIndex]||roles[roles.length-1]}. It must feel like part of one coordinated campaign while adding new information. Do not repeat copy or composition from other slides. Uploaded reference ${sourceFocus+1} is the priority visual reference for this slide; make it clearly recognizable.`:'';return `${SYSTEM_STYLE}\n\nOUTPUT: ${platform||'Instagram square'}, polished 1:1 social post.\nCREATIVE INTENT: ${template||'Product Spotlight'}.${carousel}\nMESSAGE SOURCE: ${concept}. ${support}\nBRAND: ${brand?.name||'the supplied brand'}; voice: ${brand?.voice||'confident, concise and premium'}.\nSOURCE MATERIALS: ${(materialNames||[]).join(', ')||'uploaded product references'}. Use these references faithfully and visibly.\n\nCOPY DIRECTION: Distill the message source into a short, polished headline; do not copy the full sentence. Prefer a product-led composition with zero supporting copy when the image communicates the idea. Never exceed the 14-word image-copy limit.\n\nCOMPOSITION: Choose one hero product view and no more than two supporting details. Avoid montage density, redundant before/after cards, arrows, UI-like labels and repeated product cutouts. Keep important content inside generous safe margins.${refinement?`\n\nEDIT REQUEST: The first uploaded image is the current approved composition. Refine that composition—not a fresh redesign—using this direction: ${refinement}. Preserve everything not requested to change and continue using the remaining uploads as product-fidelity references.`:''}`}
export default async function handler(req,res){
  let origin=allowedOrigin(req);if(origin)res.setHeader('Access-Control-Allow-Origin',origin);
  if(req.method==='OPTIONS'){if(!origin)return res.status(403).end();res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization');return res.status(204).end()}
  if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});
  if(!origin)return res.status(403).json({error:'Origin not allowed'});
  if(!authorized(req))return res.status(401).json({error:'Invalid generation access key'});
  if(!process.env.OPENAI_API_KEY||!process.env.GENERATION_ACCESS_KEY)return res.status(500).json({error:'Backend secrets are not configured'});
  try{
    const{image,images,idea,template,platform,brand,refinement,materialNames,count:requestedCount,carousel}=req.body||{},sources=(Array.isArray(images)?images:[image]).filter(Boolean).slice(0,4),count=refinement?1:Math.max(1,Math.min(6,Number(requestedCount)||1));
    if(!sources.length||sources.some(x=>!x.startsWith('data:image/')||x.length>6_000_000))return res.status(400).json({error:'Add up to four valid product-reference images'});
    const createSlide=async slideIndex=>{let focus=slideIndex%sources.length,ordered=[sources[focus],...sources.filter((_,i)=>i!==focus)],response=await fetch('https://api.openai.com/v1/images/edits',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:'gpt-image-2',images:ordered.map(image_url=>({image_url})),prompt:promptFor({idea,template,platform,brand,refinement,materialNames,slideIndex,slideCount:count,sourceFocus:focus}),n:1,size:'1024x1024',quality:'high',output_format:'jpeg',output_compression:90})}),body=await response.json();if(!response.ok)throw new Error(body?.error?.message||`Slide ${slideIndex+1} generation failed`);let x=body.data?.[0];if(!x?.b64_json)throw new Error(`Slide ${slideIndex+1} returned no image`);return{slideIndex,src:`data:image/jpeg;base64,${x.b64_json}`,width:1024,height:1024,style:count>1?`Carousel slide ${slideIndex+1}`:'Generated result',platform:platform||'Instagram'}};
    let settled=[];for(let start=0;start<count;start+=2){let indexes=Array.from({length:Math.min(2,count-start)},(_,i)=>start+i),batch=await Promise.allSettled(indexes.map(createSlide));settled.push(...batch.map((result,i)=>({result,index:indexes[i]})))}let outputImages=settled.filter(x=>x.result.status==='fulfilled').map(x=>x.result.value).sort((a,b)=>a.slideIndex-b.slideIndex),failedSlides=settled.filter(x=>x.result.status==='rejected').map(x=>({slide:x.index+1,error:x.result.reason?.message||'Generation failed'}));if(!outputImages.length)throw new Error(failedSlides[0]?.error||'No requested images could be generated');return res.status(200).json({images:outputImages,requested:count,failedSlides,partial:failedSlides.length>0});
  }catch(error){return res.status(500).json({error:error.message||'Generation failed'})}
}
